### ISSUE TITLE
Genome build?

### ISSUE THREAD

**Issue by PDRohde** [totajuliusd/topr#1]
Hi - what genome build does the annotation function use?

Best
Palle

**Comment by totajuliusd** [comment]
Hi Palle, it uses gene and exon information from Ensembl (build **GRCh38.p13**)

Bw
Tota

**Comment by PDRohde** [comment]
Great thanks.  
Any plan to implement an argument that allow one to choice between GRCh37 and GRCh38 ?
Best
Palle

**Comment by totajuliusd** [comment]
We are in the process of updating the package, and we can add the option to choose between builds in the new release which will be out shortly.

**Comment by totajuliusd** [comment]
Hi, I forgot to close your issue, but genome build GRCh37 was added in topr verstion 1.1.0.  You can use the **build**  (e.g build=37) argument in any of _topr´s_ functions to change to build 37.

**Comment by totajuliusd** [comment]
Hi, I forgot to close your issue, but genome build GRCh37 was added in topr verstion 1.1.0. You can use the build (e.g build=37) argument in any of topr´s functions to change to build 37.
