### ISSUE TITLE
Coloured box missing on chr 22 when no chrX in data set

### ISSUE THREAD

**Issue by amymariemason** [totajuliusd/topr#14]
Hello!

Lovely package, but I'm having an issue with manhattan plots when my dataset doesn't contain chrX. The highlight box on chr 22 doesn't appear - I suspect because it is missing a bound?

Can reproduce this with 

manhattan(CD_UKBB[CD_UKBB$CHROM!="chrX",]) 

![image](https://github.com/totajuliusd/topr/assets/19505214/11f44104-abc4-4285-9179-626fa7bbb94b)

**Comment by totajuliusd** [comment]
Thank you Amy for pointing this out. I looks like this bug was introduced in the last version of topr. I will fix this within the next 1-2 days and release version 1.1.8 where this wont be a problem.

**Comment by totajuliusd** [comment]
This issue has been fixed in _topr_ version 1.1.8 which is available on CRAN as of from today.
