### ISSUE TITLE
Plotting very small p-values

### ISSUE THREAD

**Issue by eavalo** [totajuliusd/topr#16]
Hi Tota,

Great package! 

I was trying to make a locuszoom style plot of a region where the strongest association signal has pvalues ~1e-400 . Since R can only represent values around ~1e-300 this does not work. 

One way to get around this would be to allow to pass the p-values as log10 transformed.

Best,

Erkka

**Comment by totajuliusd** [comment]
Hi Erkka and thank you for pointing this out and coming up with the solution to this problem. This will be fixed in the next version of topr which will be released soon.
Thanks,
Tota

**Comment by dhamelse** [comment]
Hi, where can I find the functionality to input significance as log10p? running into the same issue, but hopeful it has been resolved!

**Comment by totajuliusd** [comment]
Hi, it has not been resolved in the current version but will be in the next one, which will be released within the next few days.

**Comment by totajuliusd** [comment]
Hi again, _topr_ v.2.0.0 is now available (here and on CRAN), and this version can take input data as log10 p-values, if you provide the functions with the following argument (**log_trans_p=F**)
