### ISSUE TITLE
Color GWAS peaks

### ISSUE THREAD

**Issue by bridgetrileygillis** [totajuliusd/topr#21]
Hello,
Is it possible to color specified peaks (ex. novel loci) in a different color in topr manhattanplot?  For example, I have 8 novel loci detected in a meta-analysis and would like to highlight those peaks, similar to this example (one highlight color is sufficient):

<img width="434" alt="Screen Shot 2023-08-28 at 5 20 47 PM" src="https://github.com/totajuliusd/topr/assets/66333254/70eb3470-bd0d-40e2-9e8a-c95c1e3c96bd">

Additionally, can I specify to only label the nearest genes for the 8 novel loci, instead of all peaks p < 5e-08?

**Comment by totajuliusd** [comment]
Hi, yes you can do this by passing your peaks as an additional dataframe to the topr function. So for example, this can be done using the inbuilt CD_UKBB dataset as follows:

_#start by annotating the variants with their nearest gene_
CD_ANNOT <- CD_UKBB %>% annotate_with_nearest_gene()
_#extract variants of interest frmo the dataset based on their nearest gene annotation._
**genes** <- CD_ANNOT %>% filter(Gene_Symbol %in% c("TTC33", "JAK2", "NOD2", "NKD1")

_#Now create the plot with your input dataset and the extracted variants (genes) - display them in red and annotate peaks with p<1e8 
manhattan(list(CD_UKBB, **genes**),  color=c("grey",**"red"**),  annotate=c(1e-100, **1e-8**), legend_labels=c("Crohn's Disease", **"Novel loci"**), shades_alpha = 0.35)

This will result in a plot like this:

![image](https://github.com/totajuliusd/topr/assets/106526694/13e4c8bb-35bc-42ff-8e5f-7ce2f84cf908)

Is this what you were after?

**Comment by bridgetrileygillis** [comment]
Yes, thank you for the code and guidance!
