### ISSUE TITLE
Error in paste(CHROM, POS, REF, ALT, sep = ":", collapse = ", ") :    object 'REF' not found

### ISSUE THREAD

**Issue by qj009** [totajuliusd/topr#30]
Hello Tota,

I got a new error here as stated in the title. I did not see it before. Could you help me to solve it? 
Or does column "REF" and "ALT" are required?

Thanks,
Qiong

**Comment by totajuliusd** [comment]
Hi Qiong, 

REF and ALT should not be required. What command are you running? And what do the first couple of lines in your input file look like?

Tota

**Comment by qj009** [comment]
Hello Tota,

Below is my code:
`topr::manhattan(list(pheno1,pheno2,pheno3), legend_labels = c("pheno1", "pheno2","pheno3"),sign_thresh = 5e-07,get_chr_lengths_from_data = T,legend_name = "GWAS Type")`

pheno1 contain four columns: "CHROM","POS","P","ID"
pheno2 and pheno3 contain 3 columns: "CHROM","POS","P"

Interestedly, it works for another two datasets, but it does not work for this datasets. I noticed a difference of this dataset: it contain 0 in p value column. Is could be the problem?

Bests,
Qiong

**Comment by totajuliusd** [comment]
You guessed right, it is the zero that is causing the problem. If you do

topr::manhattan(list(pheno1 < filter(P>0),.... etc. 

it should work. So you can do that until I fix this and re-release?

Thank you for finding and telling me about this bug!

Bw
Tota

**Comment by qj009** [comment]
It works after filter out the rows with P value = 0. I probably will change those values to some reasonable numbers. Thank you!
