### ISSUE TITLE
Labels for Y chromosome, NA

### ISSUE THREAD

**Issue by Hugo-Biolizard** [totajuliusd/topr#31]
Hi
Big fan of the integration of annotation into the manhattan plot. However, I'm having some issues using topr version 1.1.10:

Using manhattan(), Y chromosome genes are not plotted (and I don't encounter mention of it in the documentation either). Is it possible to add another label after X? Or do you know of a workaround?

Similarly, I think it would be useful to have another label for the variants that have a (significant) p value but have NA in the CHROM column for whatever reason.

Best regards

**Comment by totajuliusd** [comment]
HI and thank you for your comment. 

You are right that you cannot plot the Y chromosome and its genes using the current version of topr. I am however working on a new release which will make it possible to use topr with multiple organisms. I can add the Y-chromosome to that version too.  It should be available shortly after Christmas or early/mid January! 
bw
Tota

**Comment by Hugo-Biolizard** [comment]
Hi Tota

I believe expanding the x-axis with Y, MT and/or unmapped would
definitely add value.
Thanks for taking the time!

Looking forward to that multi-species feature as well.
I hope that it will not be too challenging mapping variants to the animal
genome builds,
as small things such as column names for those are not always as consistent
in my experience.

Good luck and have a nice end of year celebration!

Best regards

Hugo

**Comment by totajuliusd** [comment]
Hi Hugo, topr v2.0.0 in now available and there you can plot Y and MT axes too. If you assign the unmapped variants a number (number of numeric chromosomes +1), then you can plot those too. Please let me know if this doesnt work as expected.

**Comment by Hugo-Biolizard** [comment]
Awesome, thanks for the update!

I will let you know if I run into any issues.

Best regards

Hugo
