### ISSUE TITLE
Inconsistent number of exons being plotted

### ISSUE THREAD

**Issue by sahirbhatnagar** [totajuliusd/topr#32]
The number of exons plotted seems to be dependent on wether the legend is shown or not. 

``` r
pacman::p_load(reprex)
pacman::p_load_gh("GenuityScience/topr")
data("R2_CD_UKBB")


# no legend seems to have more exons plotted
locuszoom(R2_CD_UKBB, 
          extract_plots = TRUE,
          protein_coding_only = TRUE, 
          show_gene_legend = FALSE)$gene_plot
#> [1] "Zoomed to region:  1:67042284-67359988"
```

![](https://i.imgur.com/WnMZdci.png)

``` r

# with legend seems to have less exons plotted
locuszoom(R2_CD_UKBB, 
          extract_plots = TRUE,
          protein_coding_only = TRUE, 
          show_gene_legend = TRUE)$gene_plot
#> [1] "Zoomed to region:  1:67042284-67359988"
```

![](https://i.imgur.com/3q3WGQO.png)

<sup>Created on 2023-12-18 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by totajuliusd** [comment]
Hi, you are using an older version of topr. This does not seem to be a problem in the most recent version of topr.

If I do, 

```
install.packages("topr")
library(topr)

 locuszoom(R2_CD_UKBB, 
       extract_plots = TRUE,
       protein_coding_only = TRUE, 
        show_gene_legend = TRUE)$gene_plot
```

I get

![image](https://github.com/totajuliusd/topr/assets/106526694/4169043d-ef54-4664-af15-0e2980807b84)

Please try this and see if this fixes your problem!
