### ISSUE TITLE
Colour configuration in qqtopr

### ISSUE THREAD

**Issue by ejade42** [totajuliusd/topr#35]
Hi, I love this package! By far the best GWAS visualisation package I've found. In most respects it's extremely customisable, which is excellent.

However, one thing that I have not been able to customise is the colour of the y = x line in qqtopr. I looked at the code and it seems to be hardcoded to "#808080" (line 63 of qqtopr.R). Is there any way this could be made customisable as an argument to the qqtopr function? 

Thank you!

**Comment by totajuliusd** [comment]
topr v.2.0.0 has been released and you can change the color of the diagonal line on the qqplot with the diagonal_line_color argument, like so:

`qqtopr(CD_UKBB, diagonal_line_color = "red")`
