### ISSUE TITLE
Multiple line thresholds on one manhattan plot

### ISSUE THREAD

**Issue by hlnicholls** [totajuliusd/topr#53]
Hi, thank you again for your help with my previous issue (and sorry I'm back already with another question!)

Is it possible in the manhattan() function to have multiple dotted line threshold on one manhattan plot? E.g. on line for 5x10-8 and one for something like 1x10-5?

**Comment by totajuliusd** [comment]
Hi and please ask away - always happy to help if I can.

And yes, you can have as many lines as you like by doing for example:

`manhattan(CD_UKBB, sign_thresh=c(1e-8,1e-10), sign_thresh_color=c("red","orange"))`

**Comment by hlnicholls** [comment]
Thank you very much, this has worked!
