### ISSUE TITLE
Mark target SNP in locuszoomplot

### ISSUE THREAD

**Issue by paulandroide** [totajuliusd/topr#86]
Hi! I like topr a lot and hopefully will be using it in future manuscrips!

Right now I am struggling with locuszoom, because as many SNPs besides my "target" are in perfect LD with this target, they all appear as purple triangles, which makes more difficult to see which one is the SNP where LD is being calculated.
Is there a way to mark the variant of interest somehow so it has another shape or something similar?

My lines:
locuszoom(snps.ld, 
          annotate = 1e-8,  
          rsids = "rs1052553",
          variant= "rs1052553",
          rsids_with_vline = "rs1052553",
          protein_coding_only = TRUE,
          show_overview = TRUE,
          show_genes = FALSE,
          show_gene_legend = FALSE,
          title = "LD with SNP rs1052553")

<img width="462" alt="Screen Shot 2024-06-19 at 16 25 57" src="https://github.com/totajuliusd/topr/assets/78987720/6afece15-ac1d-493d-9879-9c44a945e0b4">

Thanks a lot!

**Comment by totajuliusd** [comment]
Hi and thank you for submitting this problem.

You cant specifically change the shape of the variant of interest, but you can display it with a different size or transparency if  you provide it as a separate dataframe to the locuszoom plot. For example:

`
#_extract the top snp_
top_snp <- R2_CD_UKBB %>% filter(ID == "rs11576518")

#_create a list of your data and the top snp and provide as input_
dat <- list(R2_CD_UKBB,top_snp)

#_and plot_
locuszoom(dat, 
annotate=c(1e-100, 1e-08), 
size=c(1.5,  3),  
alpha=c(0.5, 1) , 
nudge_y=2, 
ymax=22, 
show_legend = F, 
show_gene_legend = F)

`
In the above code, I set annotate to 1e-100 for variants in the first dataframe so nothing gets annotated there. I then set the size to 1.5 for variants in the first dataframe and the size of the top variant to 3.  
I then set nudge_y to 2 to create a line between the top variant and its label.

I hope that helps.

![image](https://github.com/totajuliusd/topr/assets/106526694/eafaab01-8849-4ce7-b104-01f26ff6f7f0)

**Comment by paulandroide** [comment]
Thanks a lot! This is very helpful.
