### ISSUE TITLE
'annotate' function

### ISSUE THREAD

**Issue by MC4R** [totajuliusd/topr#87]
Hi,

Thank you very much for this wonderful package. I find it very helpful for visualizing GWAS results. 

I noticed that the `annotate` feature only annotates one locus when two signals are very close to each other. Is there a way to label the top variant from each region, irrespective of how close it is to another signal in that region?

Cheers
Dev

**Comment by totajuliusd** [comment]
Hi and thank you. The region_size argument controls the density of the labelling and its set to 10mb by default. Can you obtain what you want by reducing it? For example by doing:

 manhattan(CD_UKBB, annotate=1e-15, **region_size = 10000**)

**Comment by MC4R** [comment]
Hi,

Thank you. This is very helpful. 

Cheers
Dev

**Comment by totajuliusd** [comment]
Yes, you can use the arguments **nudge_y** and **nudge_x** to move the labels.  If setting just those parameter doesnt suffice, you can do something like this:

```
top_hits <- topr::CD_UKBB %>% get_lead_snps()
df1 <- top_hits[seq(1, nrow(top_hits), by = 2), ]
df2 <- top_hits[seq(2, nrow(top_hits), by = 2), ]

manhattan(list(CD_UKBB, df1, df2), annotate=c(1e-30, 1e-9, 1e-9), color=rep("darkblue", 3), nudge_x=c(0, -10000000, 10000000), nudge_y=c(0, 2, 1), show_legend=F)
```

![image](https://github.com/user-attachments/assets/c38ee598-1e4a-43de-adc5-ff7606d40679)

**Comment by MC4R** [comment]
Thank you very much.
